version: "3.0"

services:
  etcd_node_1:
    build:
      context: ./etcd  # 镜像
    container_name: etcd_node_1       # 容器名 --name
    restart: always             # 总是重启
    networks:
      - etcd-net                # 使用的网络 --network
    ports: # 端口映射 -p
      - "${ETCD_NODE_1_CLIENT_PORT}:2379"
      - "${ETCD_NODE_1_NODE_PORT}:2380"
    environment: # 环境变量 --env
      - ALLOW_NONE_AUTHENTICATION=yes                       # 允许不用密码登录
      - ETCD_NAME=etcd_node_1                                     # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_node_1:2380  # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380           # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379         # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_node_1:2379        # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd_node_1=http://etcd_node_1:2380,etcd_node_2=http://etcd_node_2:2380,etcd_node_3=http://etcd_node_3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                      # 初始化集群状态
    volumes:
      - etcd_node_1_data:/bitnami/etcd                            # 挂载的数据卷

  etcd_node_2:
    build:
      context: ./etcd
    container_name: etcd_node_2
    restart: always
    networks:
      - etcd-net
    ports:
      - "${ETCD_NODE_2_CLIENT_PORT}:2379"
      - "${ETCD_NODE_2_NODE_PORT}:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd_node_2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_node_2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_node_2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd_node_1=http://etcd_node_1:2380,etcd_node_2=http://etcd_node_2:2380,etcd_node_3=http://etcd_node_3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd_node_2_data:/bitnami/etcd

  etcd_node_3:
    build:
      context: ./etcd
    container_name: etcd_node_3
    restart: always
    networks:
      - etcd-net
    ports:
      - "${ETCD_NODE_3_CLIENT_PORT}:2379"
      - "${ETCD_NODE_3_NODE_PORT}:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd_node_3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd_node_3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_node_3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd_node_1=http://etcd_node_1:2380,etcd_node_2=http://etcd_node_2:2380,etcd_node_3=http://etcd_node_3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd_node_3_data:/bitnami/etcd

networks:
  etcd-net: # 网络
    driver: ${NETWORKS_DRIVER}    # 桥接模式

volumes:
  etcd_node_1_data: # 挂载到本地的数据卷名
    driver: ${VOLUMES_DRIVER}
  etcd_node_2_data:
    driver: ${VOLUMES_DRIVER}
  etcd_node_3_data:
    driver: ${VOLUMES_DRIVER}